### ISSUE TITLE
[stale-dep] Your node_modules is stale. Please run yarn first. 

### ISSUE THREAD

**Issue by trollepierre** [sxzz/stale-dep#40]
### Describe the bug

While running "yarn install && npx stale-dep", I faced the ERROR [stale-dep] Your node_modules is stale. Please run yarn first. 

I don't know what is going wrong.

### Reproduction

Run "yarn install && npx stale-dep" inside my 2 private packages (front and back)

### System Info

```Shell
System:
    OS: macOS 12.6.7
    CPU: (8) arm64 Apple M1 Pro
    Memory: 118.69 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.7.6 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 117.0.5938.92
    Edge: 117.0.2045.40
    Safari: 16.5.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Run `stale-dep -u` after every install. Or adding `postinstall` hook.
See docs https://github.com/sxzz/stale-dep?tab=readme-ov-file#add-stale-dep-to-the-project
